version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - app-network
    volumes:
      - ./:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  jupyter:
    image: jupyter/minimal-notebook
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: jupyter_notebook


networks:
  app-network:

volumes:
  redis_data: