version: '3.8'

services:
  api:
    build:
      dockerfile: ./docker/api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - app-network
    volumes:
      - ./:/app
    container_name: api

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    container_name: redis

  jupyter:
    build:
      dockerfile: ./docker/jupyter
    volumes:
      - ./work:/home/jovyan/work
    networks:
      - app-network
    ports:
      - 8888:8888
    user: root
    environment:
      NB_USER: "root"
      NB_UID: 0
      NB_GID: 0
      NOTEBOOK_ARGS: --allow-root
    command: "start-notebook.sh --NotebookApp.token="
    container_name: jupyter_notebook


networks:
  app-network:

volumes:
  redis_data: